global:
  scrape_interval: 5s # Scrape frequently for demo purposes

scrape_configs:
  - job_name: "churn-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["churn-api:8000"] # Matches the service name in docker-compose