data_ingestion:
  root_dir: data
  raw_data_dir: data/raw
  train_data_file: train_v2.csv
  members_data_file: members_v3.csv
  transactions_data_file: transactions_v2.csv
  user_logs_data_file: user_logs_v2.csv